# Generated by Django 3.1 on 2020-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200818_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
