# Generated by Django 3.1 on 2020-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200818_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecipes',
            name='instructions',
            field=models.CharField(default=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='popularrecipes',
            name='instructions',
            field=models.CharField(default=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='popularrecipes',
            name='description',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
