# Generated by Django 3.1 on 2020-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200818_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecipes',
            name='instructions',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='popularrecipes',
            name='instructions',
            field=models.TextField(default=True),
        ),
    ]
