# Generated by Django 3.1 on 2020-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200818_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularrecipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
