# Generated by Django 3.1 on 2020-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_popularrecipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecipes',
            name='level',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='customerrecipes',
            name='time_needed',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='popularrecipes',
            name='level',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='popularrecipes',
            name='time_needed',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
