# Generated by Django 3.1 on 2020-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200819_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecipes',
            name='ingredients',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='popularrecipes',
            name='ingredients',
            field=models.TextField(default=True),
        ),
    ]
