# Generated by Django 3.1 on 2020-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200819_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecipes',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2020-8-17'),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='level',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerrecipes',
            name='time_needed',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
